name: Auto-Complete Overdue Events

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  auto-complete:
    runs-on: ubuntu-latest
    
    steps:
      - name: Auto-complete overdue events
        run: |
          curl -X POST "${{ secrets.SUPABASE_URL }}/functions/v1/auto-complete-events" \
            -H "Authorization: Bearer ${{ secrets.AUTO_COMPLETE_API_KEY }}" \
            -H "Content-Type: application/json" \
            --fail-with-body \
            --show-error \
            --silent \
            --output response.json
          
          echo "Response:"
          cat response.json
          
          # Check if the request was successful
          if ! jq -e '.success == true' response.json > /dev/null; then
            echo "Auto-completion failed!"
            exit 1
          fi
          
          echo "Auto-completion completed successfully!"

      - name: Upload response as artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: auto-complete-response
          path: response.json 